### ISSUE TITLE
shut down a redis server

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/bespoke-fit#179]
So I was trying to run something but I noticed that I did something wrong. So I use control+C to terminate the run. Then if I try to start a new run, I would get
```
[ERROR] a redis server is already running at host=localhost and port=6363, continuing to run would likely causeunintended consequences.
⠋ launching the bespoke executor
```
I wonder how do I terminate the redis server? Thank you.

**Comment by jthorton** [comment]
Hi @xiki-tempula, BespokeFit should normally clear these processes up but sometimes they can get left around the best thing to do is to use the redis cli to close the server, something like `redis-cli -p 6363` and then type shutdown should stop the server.

**Comment by xiki-tempula** [comment]
@jthorton Thanks. Would it be better to 
if the same port is being used, shut down the process before starting a new run.
Or
if the same port is being used, use a new port?.

**Comment by jthorton** [comment]
@xiki-tempula yes we did think about this but we do offer support for users to have long-running BespokeFit redis servers for large-scale production fits and it might not be safe to always close down the server hence the warning.  

> if the same port is being used, use a new port?

Yes that's true and you can configure that with an [environment variable](https://github.com/openforcefield/openff-bespokefit/blob/1421638393b918161e6f58f49da483dfad06d577/openff/bespokefit/executor/services/_settings.py#L31) we don't do this automatically, however, in case we leave a lot of redis-servers around from processes which don't shut down correctly which can happen now and again.
