### ISSUE TITLE
About the way soft torsion are identified

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/bespoke-fit#181]
I'm interested in how bespokefit identifies the soft torsions to be scanned or exclude the hard torsions to not be scanned. 
I wonder if there is any documentation for that?
If there is no documentation for that, I wonder if i could be pointed towards the part of the code that does.
Thank you.

**Comment by xiki-tempula** [comment]
@j-wags Thank you. Does this SMIRKS pattern captures everything? Like it wouldn't recognise the dihedral in cyclopropane or dihedrals in cyclo molecules in general (as these won't go well with torsion scan).
And you don't do any downstream heuristics to do more filtering.

**Comment by j-wags** [comment]
> Like it wouldn't recognise the H-C-C-H dihedral in cyclopropane or dihedrals in cyclo molecules in general (as these won't go well with torsion scan).

The current value of the target torsion SMIRKS is `'[!#1]~[!$(*#*)&!D1:1]-,=;!@[!$(*#*)&!D1:2]~[!#1]'`. The part that describes the central bond is `-,=;!@`, which (I'm pretty sure) means "the central bond is single or double (`-,=`), and must not be in a ring (`;!@`)". So it should exclude all ring bonds.

>  And you don't do any downstream heuristics to do more filtering.

I don't think we do additional filtering, but I have low confidence in this answer, so I might escalate that question to @jthorton (who is out right now, so he may not get back to us on this for a few days).

**Comment by jthorton** [comment]
Hi @xiki-tempula, @j-wags is correct the SMIRKS pattern he shows is the only thing we use to identify torsions which should be targeted for optimisation and this is a fully customisable option in the workflow, we accept a list of patterns which can describe the target torsions so if you have a case in mind which is not hit by BespokeFit you can add a pattern for it to the list but this may uncover some issues when trying to scan in-ring torsions.
