### ISSUE TITLE
"IndexError: list index out of range" when no fragments are generated by fragmentation_engine

### ISSUE THREAD

**Issue by rvkrishnan30** [openforcefield/bespoke-fit#40]
Building a schema with molecules like ethanol failed at  

```

from openff.bespokefit.workflows import bespoke
workflow = bespoke.BespokeWorkflowFactory(
    initial_force_field="openff_unconstrained-1.3.0.offxml", 
)

from openff.toolkit.topology import Molecule 
eth_mol = Molecule.from_smiles("CCO")
schema = workflow.optimization_schema_from_molecule(molecule=eth_mol)

```
with the following error: 

```
bespoke-fit/openff/bespokefit/workflows/bespoke.py in optimization_schema_from_molecule(self, molecule, index)
394         # the parent molecule is put in canonical order by fragmenter to use the new parent
395         attributes = MoleculeAttributes.from_openff_molecule(
--> 396             molecule=fragment_data[0].parent_molecule
397         )
398         molecule_schema = MoleculeSchema(
IndexError: list index out of range

```

I'm guessing perhaps adding a condition to check for fragments after calling the fragmentation_engine and if none generated to directly proceed with the parent molecule could fix this.

**Comment by jthorton** [comment]
@rvkrishnan30 thanks for reporting this I aim to get the exception fixed ASAP. For molecules like this fragmenter is actively ignoring the terminal groups as they should be well represented by the base forcefield see [here](https://github.com/openforcefield/openff-fragmenter/blob/4a290b866a8ed43eabcbd3231c62b01f0c6d7df6/openff/fragmenter/fragment.py#L299). So only molecules with these terminal groups should hit this error so I don't think there is much value in scanning the bonds.

**Comment by rvkrishnan30** [comment]
@jthorton, thank you for the explanation. 
A related case where fragments are not generated and subsequently schema generation fails is this molecule ("[H][O][C]([C]([H])([H])[H])([C]([H])([H])[H])[C]([H])([H])[N]([H])[C]1=[N][C]2=[C]([C]([H])=[N]1)[C]([H])=[C]([O][C]1=[C]([F])[C]([H])=[C]([F])[C]([H])=[C]1[H])[C](=[O])[N]2[C]([H])([H])[H]") where schema generation failed as the stereochemistry of a fragment could not be fixed during fragmentation. 

These are the type of cases (probably not exceptions) where having a condition to continue building the schema as if the parent molecule is the fragment and process its rotatable bonds could help in the absence of fragmentation. 

```
bespoke-fit/openff/fragmenter/fragment.py in _fix_stereo(cls, fragment, parent_stereo)
    243         raise RuntimeError(
--> 244             f"The stereochemistry of {fragment.to_smiles()} could not be fixed."
    245         )

RuntimeError: The stereochemistry of [H][O][C]([H])([C]([H])([H])[H])[C]([H])([H])[N]([H])[c]1[n][c]([H])[c]2[c]([n]1)[N]([C]([H])([H])[H])[C](=[O])[C]([O][c]1[c]([H])[c]([H])[c]([F])[c]([H])[c]1[F])=[C]2[H] could not be fixed.

During handling of the above exception, another exception occurred:

/bespoke-fit/openff/bespokefit/fragmentation/fragmenter.py in fragment(self, molecule)
     70         except RuntimeError:
     71             raise FragmenterError(
---> 72                 f"The molecule {molecule} could not be fragmented so no fitting target "
     73                 f"was made."
     74             )

FragmenterError: The molecule Molecule with name '' and SMILES '[H][O][C]([C]([H])([H])[H])([C]([H])([H])[H])[C]([H])([H])[N]([H])[c]1[n][c]([H])[c]2[c]([n]1)[N]([C]([H])([H])[H])[C](=[O])[C]([O][c]1[c]([H])[c]([H])[c]([F])[c]([H])[c]1[F])=[C]2[H]' could not be fragmented so no fitting target was made.
```
