### ISSUE TITLE
SnowFlake Reliability 

### ISSUE THREAD

**Issue by jthorton** [openforcefield/bespoke-fit#5]
The Snowflake qcfractal instance can be unreliable sometimes so we have added support to export QCSubmit datasets that can be run in a persistent QCArchive instance. We should also work on making the SnowFlake more reliable and configurable to support quick QC/ML scans. 

- [ ] add controls so the user can chose how many workers to spin up and how much memory and cores they each get.
- [ ] Add tests for the snowflake server to catch common issues
- [ ] Make sure only one instance of the server is used at any time, as some stages use multiprocessing this could be copying the database.

**Comment by SimonBoothroyd** [comment]
I think we can close this @jthorton as we don't use a snowflake any more?

**Comment by jthorton** [comment]
Good point we have a much more reliable QC generation method now!
