### ISSUE TITLE
Gaff support

### ISSUE THREAD

**Issue by kexul** [openforcefield/bespoke-fit#82]
Dear openff developers, is it possible to use gaff as the initial force field? I tried to set it by the following code:
```
from openff.bespokefit.workflows import BespokeWorkflowFactory

workflow = BespokeWorkflowFactory(
    fragmentation_engine=None,
    optimizer=fb,
    parameter_hyperparameters=[],
    target_templates=[],
    default_qc_specs=[]
)
workflow.initial_force_field = 'data/gaff-2.1.xml'
```
The `gaff-2.1.xml` was downloaded from [here](https://github.com/openmm/openmmforcefields/tree/master/amber/gaff/ffxml) , here is the error message: 
 
```
OSError: Source data/gaff-2.1.xml could not be read. If this is a file, ensure that the path is correct.
If the file is present, ensure it is in a known SMIRNOFF encoding.
Valid formats are: ['XML']
Parsing failed with the following error:
not well-formed (invalid token): line 1, column 4
```

**Comment by j-wags** [comment]
Hi @kexul,

Unfortunately, BespokeFit can't use GAFF as the initial force field right now. The [OFFXML file format](https://open-forcefield-toolkit.readthedocs.io/en/latest/users/smirnoff.html) is fundamentally different from the OpenMM serialized ForceField format. The OFFXML format describes how to apply parameters to a "chemical" representation of a molecule (described by elements, formal charges, and bond orders) whereas the `gaff-2.1.xml` file is applied to atom-typed molecules (where the element+formal charge+bond order information has been replaced by the assignment of atom types).

Using an OpenMM `ForceField` as a starting point for bespoke fitting isn't fundamentally impossible, however it will take a lot of work, so I don't anticipate us rolling out support for it in the next year or two.

**Comment by kexul** [comment]
Thanks for your detailed answer!
